import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SideBar } from "@/components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen w-ful flex  antialiased`}
      >
        <SideBar></SideBar>
        <main className="bg-gray-50 p-4 w-full font-sans text-gray-900 sm:p-6 md:p-8">
          <div className="mx-auto w-full max-w-[1650px]">{children}</div>
        </main>
      </body>
    </html>
  );
}
